language: bash
services: docker

env:
  - PHP_VERSION=7.2
  - PHP_VERSION=7.3

before_script:
  - env | sort
  - IMAGE="nginx-php:${PHP_VERSION}-alpine"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t ${IMAGE} --build-arg PHP_VERSION=${PHP_VERSION} .
      docker images
      echo ${HUB_PASSWORD} | docker login -u ${HUB_USERNAME} --password-stdin
      docker tag ${IMAGE} ${HUB_USERNAME}/${IMAGE}
      docker push ${HUB_USERNAME}/${IMAGE}
    )
  - |
    if [ ${PHP_VERSION} == "7.3" ]; then
      docker tag ${IMAGE} ${HUB_USERNAME}/nginx-php:7;
      docker tag ${IMAGE} ${HUB_USERNAME}/nginx-php:latest;
      docker push ${HUB_USERNAME}/nginx-php:7;
      docker push ${HUB_USERNAME}/nginx-php:latest;
    fi

