language: bash
services: docker

env:
  - PHP_VERSION=7.1 GD="--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
  #- PHP_VERSION=7.2 GD="--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
  #- PHP_VERSION=7.3 GD="--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
  #- PHP_VERSION=7.4 GD=""

before_script:
  - env | sort
  - IMAGE="nginx-php:${PHP_VERSION}"
  - HUB_IMAGE=${HUB_USERNAME}/${IMAGE}

script:
  - docker pull ${HUB_IMAGE} || true
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t ${IMAGE} --build-arg PHP_VERSION=${PHP_VERSION} --build-arg GD="${GD}" --pull --cache-from ${HUB_IMAGE} .
      docker images
    )
  - |
    (
      set -Eeuo pipefail
      set -x
      PHP_MINOR=`docker run corbosman/${IMAGE} php -v | grep ^PHP | cut -d' ' -f2`
    )
  - |
    (
    set -Eeuo pipefail
    set -x
    if [ ${TRAVIS_BRANCH} == 'master' ]; then
      docker login -u ${HUB_USERNAME} -p ${HUB_PASSWORD}
      docker tag ${IMAGE} ${HUB_IMAGE}
      docker push ${HUB_IMAGE}
      if [ ${PHP_VERSION} == "7.4" ]; then
        docker tag ${IMAGE} ${HUB_USERNAME}/nginx-php:7;
        docker tag ${IMAGE} ${HUB_USERNAME}/nginx-php:latest;
        docker push ${HUB_USERNAME}/nginx-php:7;
        docker push ${HUB_USERNAME}/nginx-php:latest;
      fi
    fi
    )
