language: bash
services: docker

before_script:
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build .
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
