name: Publish Docker Image

on:
  push:
  pull_request:

jobs:
  push-to-docker-hub:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        include:
           - php: 7.1
             gd: "--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
           - php: 7.2
             gd: "--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
           - php: 7.3
             gd: "--with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/ --with-gd"
           - php: 7.4
             gd: ""

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Pull Cache Image
        run: docker pull corbosman/nginx-php:${{matrix.php}} || true

      - name: Build PHP${{matrix.php}} Image
        run: docker build -t nginx-php:${{matrix.php}} --build-arg PHP_VERSION=${{matrix.php}} --build-arg GD="${{matrix.gd}}" --pull --cache-from corbosman/nginx-php:${{matrix.php}} .

      - name: Build Minor Version For PHP${{matrix.php}}
        run: |
          PHP_VERSION_MINOR=${{matrix.php}}.1
          docker build -t nginx-php:${{PHP_VERSION_MINOR}} --build-arg  PHP_VERSION=${{matrix.php}} --build-arg GD="${{matrix.gd}}" --pull --cache-from corbosman/nginx-php:${{matrix.php}} .
